docs: add ARCHITECTURE.md
kubewarden/audit-scanner pull request #285
Opened 2024-05-28 13:43 UTC by flavio

Explain how the audit-scanner performs the scan.

### Possibile improvements

1. Instead of doing Namespace auditing sequentially, allow for parallel auditing of namespaces. Expose a flag for that
2. Inside of a Namespace, keep auditing resources in parallel, but instead of hard coding the number of resources being audited in parallel, expose a flag for that
3. When auditing a specific resource (like a specific `Pod`), instead of evaluating each policy sequentially, evaluate them in parallel. Expose a flag for that

2024-05-28 16:49 UTC, jvanz requested changes

2024-05-28 16:49 UTC, jvanz commented on ARCHITECTURE.md
> +This a map similar to the one created for the cluster-wide resources. However, in this case the types of policies associated with a Kubernetes
```suggestion
This map is similar to the one created for the cluster-wide resources. However, in this case the types of policies associated with a Kubernetes
```

2024-05-29 05:52 UTC, fabriziosestito commented on ARCHITECTURE.md
> +- Create a fake `CREATE` event for that resource, send it to the Policy Server that hosts the policy, and get the response
`event` may be ambiguous (see kubernetes events). we are forging an AdmissionReview/Admissionrequest with a CREATE operation

2024-05-29 08:51 UTC, flavio commented
Merging, I've addressed all the comments. Thanks!

2024-05-29 08:51 UTC, merged