feat: Save reports to cluster, add new `--print` flag to print them as JSON
kubewarden/audit-scanner pull request #42
Opened 2023-06-05 15:41 UTC by viccuad

## Description

Fix https://github.com/kubewarden/audit-scanner/issues/36

Save all reports to cluster.
Add a new `--print` flag: these flag prints the results to stdout as JSON, in addition to what the audit-scanner is doing.

## Test

Manual, see CONTRIBUTING.md

## Additional Information

### Tradeoff

### Potential improvement

This PR could include the first e2e tests for audit scanner.

2023-06-05 18:12 UTC, jvanz requested changes

2023-06-06 08:56 UTC, viccuad commented on internal/report/store.go
> +func (s *PolicyReportStore) savePolicyReport(report *PolicyReport) error {
true! done in https://github.com/kubewarden/audit-scanner/pull/42/commits/d6e7550e9146a17a0f7b1c10e8c3a8e80d232ad0.

2023-06-06 08:56 UTC, viccuad commented on internal/report/store.go
> +func (s *PolicyReportStore) saveClusterPolicyReport() error {
true! done in https://github.com/kubewarden/audit-scanner/pull/42/commits/d6e7550e9146a17a0f7b1c10e8c3a8e80d232ad0.

2023-06-06 08:57 UTC, viccuad commented on internal/report/store.go
> +			//
I have refactored the error handling of SaveAll() and the other 2 Save* functions, see https://github.com/kubewarden/audit-scanner/pull/42/commits/957144c86503b664353e633e3993f74f3d73397b.
Now they bubble up errors correctly.

2023-06-06 09:19 UTC, flavio requested changes

2023-06-06 10:29 UTC, viccuad commented on internal/report/store.go
> +		log.Error().Err(err).
Done in https://github.com/kubewarden/audit-scanner/pull/42/commits/ad050f45c91be6f9cd87801f030f00800bb57453!

2023-06-06 12:02 UTC, flavio approved these changes
Thanks for having submitted the changes requested :heart:

2023-06-06 15:15 UTC, merged